version: '3.7'
services:
  vtk-converter:
    build:
      context: ./
      dockerfile: docker/python/Dockerfile
      labels:
        io.simcore.name: '{"name":"VTK Converter"}'
        io.simcore.thumbnail: '{"thumbnail":"https://github.com/ITISFoundation/osparc-assets/blob/cb43207b6be2f4311c93cd963538d5718b41a023/assets/default-thumbnail-cookiecutter-osparc-service.png?raw=true"}'
        io.simcore.description: '{"description":"Module to convert .vtk files to their
          .stl and .oents"}'
        io.simcore.key: '{"key":"simcore/services/comp/vtk-converter"}'
        io.simcore.version: '{"version":"0.1.0"}'
        io.simcore.integration-version: '{"integration-version":"1.0.0"}'
        io.simcore.type: '{"type":"computational"}'
        io.simcore.authors: '{"authors":[{"name":"Shailesh Appukuttan","email":"appukuttan.shailesh@gmail.com","affiliation":"INT,
          Aix-Marseille University, France"}]}'
        io.simcore.contact: '{"contact":"appukuttan.shailesh@gmail.com"}'
        io.simcore.inputs: '{"inputs":{"input_1":{"displayOrder":1.0,"label":"source
          .vtk file","description":"vtk file to be converted","type":"data:*/*"}}}'
        io.simcore.outputs: '{"outputs":{"output_1":{"displayOrder":1.0,"label":".stl
          file","description":"Converted .stl file","type":"data:*/*","fileToKeyMap":{"scaffold.stl":"output_1"}},"output_2":{"displayOrder":2.0,"label":".obj
          file","description":"Converted .obj file","type":"data:*/*","fileToKeyMap":{"scaffold.obj":"output_2"}}}}'
        org.label-schema.build-date: 2024-08-11T23:40:41+0000
        org.label-schema.schema-version: '1.0'
        org.label-schema.vcs-ref: ''
        org.label-schema.vcs-url: ''
        simcore.service.restart-policy: no-restart
        simcore.service.settings: '[{"name":"Resources","type":"Resources","value":{"Limits":{"NanoCPUs":1000000000,"MemoryBytes":2147483648}}}]'
      target: production
    image: simcore/services/comp/vtk-converter:0.1.0
